### ISSUE TITLE
`date_part` does't work for `now()`

### ISSUE THREAD

**Issue by waitingkuo** [apache/arrow-datafusion#3096]
**Describe the bug**

**To Reproduce**

```bash
❯ select date_part('hour', now());
Plan("Coercion from [Utf8, Timestamp(Nanosecond, Some(\"UTC\"))] to the signature OneOf([Exact([Utf8, Date32]), Exact([Utf8, Date64]), Exact([Utf8, Timestamp(Second, None)]), Exact([Utf8, Timestamp(Microsecond, None)]), Exact([Utf8, Timestamp(Millisecond, None)]), Exact([Utf8, Timestamp(Nanosecond, None)])]) failed.")
```

note that it could be fixed by 
```bash
❯ select date_part('hour', now()::timestamp);
+-------------------------------------------------------------------+
| datepart(Utf8("hour"),CAST(now() AS Timestamp(Nanosecond, None))) |
+-------------------------------------------------------------------+
| 6                                                                 |
+-------------------------------------------------------------------+
1 row in set. Query took 0.000 seconds.
```

the reason for that is `now()` output `timestamp with time zone`, but our `date_part` doesn't work for it

**Expected behavior**

**Additional context**

**Comment by waitingkuo** [comment]
extract has the same behavior

```bash
❯ select extract(hour from now());
Plan("Coercion from [Utf8, Timestamp(Nanosecond, Some(\"UTC\"))] to the signature OneOf([Exact([Utf8, Date32]), Exact([Utf8, Date64]), Exact([Utf8, Timestamp(Second, None)]), Exact([Utf8, Timestamp(Microsecond, None)]), Exact([Utf8, Timestamp(Millisecond, None)]), Exact([Utf8, Timestamp(Nanosecond, None)])]) failed.")

❯ select extract(hour from now()::timestamp);
+-------------------------------------------------------------------+
| datepart(Utf8("HOUR"),CAST(now() AS Timestamp(Nanosecond, None))) |
+-------------------------------------------------------------------+
| 6                                                                 |
+-------------------------------------------------------------------+
1 row in set. Query took 0.000 seconds.
```

**Comment by turbo1912** [comment]
Hello @waitingkuo, is anyone working on this? If not I can try this one (maybe this is even fixed with some of the other recent timestamp fixes)

**Comment by waitingkuo** [comment]
@turbo1912 i'm not working on this. It's not fixed yet, we could only cast `Timestamp(Nanosecond, Some(\"UTC\")` to `Timestamp(Nanosecond, None)` for now.

**Comment by comphead** [comment]
@waitingkuo I'd pick this up if no objections
