### ISSUE TITLE
TPCH, Query 18 and 17 very slow

### ISSUE THREAD

**Issue by djouallah** [apache/arrow-datafusion#5646]
was running a TPCH_SF5 just for fun, I notice query 17 and 18 are very slow

full reproducible example

another issue when I increase sf to 10, I start getting OOM errors ?

https://colab.research.google.com/drive/1WJ2ICxJyAYClkDx8guGX-TcOMnf8SBxr#scrollTo=z494Cl6XKUVX

DataFusion 26 gives the following result against duckdb

![image](https://github.com/apache/arrow-datafusion/assets/12554469/d862a903-7ad4-4086-a56e-a8e1af0a2280)

**Comment by mingmwang** [comment]
I will take a look.

**Comment by mingmwang** [comment]
Working on it now.  I am not sure whether it is regression or those two queries are always slow.

**Comment by mingmwang** [comment]
The bottle neck is parquet reader and hash building.

**Comment by Dandandan** [comment]
A profile run using flamegraph shows on my machine:

`cast::cast_decimal_to_decimal` is consuming about 1/4 of the time of q17.

**Comment by Dandandan** [comment]
![flamegraph](https://user-images.githubusercontent.com/163737/229604055-4c318065-1db2-4ebc-a031-ebb056bdba83.svg)

**Comment by Dandandan** [comment]
FYI @viirya

**Comment by mingmwang** [comment]
One reason for so many `downcast_value` call is because the grouping column `l_partkey` is with high cardinality, causing the vectorization is almost useless.

**Comment by Dandandan** [comment]
The most expensive part is the line `let values = &cast(values, sum_type)?` in `sum_batch` which performs this casting.

I guess we should move that evaluation (or other parts of `sum_batch` as well) up, so it will be done before the grouping, rather than after.

**Comment by Dandandan** [comment]
Another observation I have is that the plan does some unnecessary casting:

```
Projection: CAST(SUM(lineitem.l_extendedprice) AS Float64) / Float64(7) AS avg_yearly
  Aggregate: groupBy=[[]], aggr=[[SUM(lineitem.l_extendedprice)]]
    Projection: lineitem.l_extendedprice
      Inner Join: part.p_partkey = __scalar_sq_3.l_partkey Filter: CAST(lineitem.l_quantity AS Decimal128(30, 15)) < CAST(__scalar_sq_3.__value AS Decimal128(30, 15))
        Projection: lineitem.l_quantity, lineitem.l_extendedprice, part.p_partkey
          Inner Join: lineitem.l_partkey = part.p_partkey
            TableScan: lineitem projection=[l_partkey, l_quantity, l_extendedprice]
            Projection: part.p_partkey
              Filter: part.p_brand = Utf8("Brand#23") AND part.p_container = Utf8("MED BOX")
                TableScan: part projection=[p_partkey, p_brand, p_container], partial_filters=[part.p_brand = Utf8("Brand#23"), part.p_container = Utf8("MED BOX")]
        SubqueryAlias: __scalar_sq_3
          Projection: lineitem.l_partkey, Float64(0.2) * CAST(AVG(lineitem.l_quantity) AS Float64) AS __value
            Aggregate: groupBy=[[lineitem.l_partkey]], aggr=[[AVG(lineitem.l_quantity)]]
              TableScan: lineitem projection=[l_partkey, l_quantity]
```

1. inside the aggregation (in `sum_batch`)
2. cast to float for `__scalar_sq_3.__value`
3. cast back to decimal inside join

**Comment by jackwener** [comment]
it's related with `type coercion`, I have a job related with it.
#5831.
This PR contains a fix for type coercion of subquery, it will move `cast` from `expression` into `subplan`. It means that we don't `cast expression` in `eval expression` and we do cast before `eval expression`.

**Comment by jackwener** [comment]
> Another observation I have is that the plan does some unnecessary casting:

@Dandandan , Yes, I also notice this problem, it's related with `type coercion`.

BTW, #5831 also is related with this, is move cast from expression eval into subplan

**Comment by Dandandan** [comment]
@jackwener Nice, thank you

**Comment by Dandandan** [comment]
@jackwener this is all resolved now, right?

**Comment by djouallah** [comment]
datafusion is doing a great progress but still, it is not solved
Version: 26.0.0

![image](https://github.com/apache/arrow-datafusion/assets/12554469/d862a903-7ad4-4086-a56e-a8e1af0a2280)

**Comment by mingmwang** [comment]
I am still working on it.

**Comment by Dandandan** [comment]
Query 18 should is also considerably faster in the next DataFusion version, because of join-related improvements (datastructure and vectorized collision checks).
I'll be looking into what we can do further.

**Comment by Dandandan** [comment]
One suggestion that will yield some (smaller) performance improvement for query 18 (and most other queries): https://github.com/apache/arrow-datafusion/issues/6768

**Comment by alamb** [comment]
There is quite a lot of recent work / proposals to make the grouping  significantly faster for these queries. See https://github.com/apache/arrow-datafusion/issues/4973

**Comment by djouallah** [comment]
using Python_datafusion 27, unfortunately still issues with Query 17, my VM has 8 cores and 64 GB of RAM, Query 17 got OOM

![image](https://github.com/apache/arrow-datafusion/assets/12554469/42e3455b-214a-4004-b7e9-4e83a58e1331)

**Comment by alamb** [comment]
I expect Q17 to go about 2x faster and use much less memory when we merge our most recent work -- see https://github.com/apache/arrow-datafusion/pull/6800#issuecomment-1627412684 for details

**Comment by djouallah** [comment]
i am doing this experimentation using fabric notebook, datafusion doing alright, would love really to start seeing numbers for 8 cores, make it works first then fast later :)
![image](https://github.com/apache/arrow-datafusion/assets/12554469/8e37d803-b7af-49dd-bff4-23b30508af9b)

**Comment by Dandandan** [comment]
Thanks @djouallah - the new `GroupHashAggregate ` approach will also (drastically) reduce memory.

**Comment by alamb** [comment]
BTW I think the reason DF's memory usage is increasing with number of cores is because the first partial aggregate phase is using RoundRobin repartitioning (and thus each hash table has an entry for all the groups). 

To avoid this, we would need to hash repartition the input based on group keys so the different partitions saw different subsets of the group keys

**Comment by djouallah** [comment]
@alamb the graph show the overall duration to finish toch_sf100 based on the number of cores, Datafusion is faster than spark even when using only 1 VM ;)

**Comment by alamb** [comment]
If you get a chance to test with the latest datafusion (will be in 28.0.0, eta probably next week) I expect performance for high cardinality grouping to be much better due to https://github.com/apache/arrow-datafusion/pull/6904

**Comment by alamb** [comment]
> BTW I think the reason DF's memory usage is increasing with number of cores is because the first partial aggregate phase is using RoundRobin repartitioning (and thus each hash table has an entry for all the groups).

I wrote up an issue describing this here: https://github.com/apache/arrow-datafusion/issues/6937

**Comment by djouallah** [comment]
using version 28, I query 8 start getting errors

https://colab.research.google.com/drive/1KzofqAWJxVTboNcywGxSbIgLNatkIsM2


```
Query8
Arrow error: Compute error: Overflow happened on: 136581719431 * 100000000000000000000000000000000000000
```

**Comment by Dandandan** [comment]
Sounds like https://github.com/apache/arrow-datafusion/issues/6794
Cc @viirya

**Comment by djouallah** [comment]
good job btw for Query 17 and 18

![image](https://github.com/apache/arrow-datafusion/assets/12554469/0237055e-beb2-4a05-a613-de5b26b2cf88)

**Comment by viirya** [comment]
> Sounds like #6794 Cc @viirya

I suppose that decimal multiplication and division precision change at #6832 will fix that.

**Comment by Dandandan** [comment]
> good job btw for Query 17 and 18, unfortunately when the RAM is limited, still Datafusion get OOM for Query 18

Nice, getting close to `DuckDB`. `hyper` is incredible for some queries!

**Comment by djouallah** [comment]
@Dandandan specially when using their native format, Hyper just literally don't care about RAM, i use it with the free colab, and did finish tpch_sf110 !!! just fine, what do you think they are doing different ?

**Comment by Dandandan** [comment]
> @Dandandan specially when using their native format, Hyper just literally don't care about RAM, i use it with the free colab, and did finish tpch_sf110 !!! just fine, what do you think they are doing different ?

Hard to say in general, but they do some optimizations we don't do or do better planning (e.g. for join selection).
Using a different format instead of parquet might help as well as parquet can be slower to decode / decompress than formats optimized for query performance.

**Comment by djouallah** [comment]
it seems there is a regression with query 18, it used to works fine with tpch100 using 124 GB of RAM, now the notebook crashes when using DF31 !!!

**Comment by alamb** [comment]
Given the long history of this issue, I think it is hard to understand what, if anything, it is tracking. I suggest we close it and file another issue to continue discussing additional performance improvements

**Comment by djouallah** [comment]
the issue is very clear, performance of Query 17 and 18 is still very slow compared to other in process engines !!
![image](https://github.com/apache/arrow-datafusion/assets/12554469/e6f6230d-c8d6-441d-8ceb-96b883af6d9e)

**Comment by djouallah** [comment]
Btw, DF31 is making a great progress, my impression as long as the data fit in memory, the performance is very similar to DuckDB, here I am reading Parquet files from an Azure storage, the main issue start with core 8 which has 64 of GB, Query 18 crash the notebook
![image](https://github.com/apache/arrow-datafusion/assets/12554469/493f8b9f-0494-4dc1-a8d1-c37d7e45ed9d)

**Comment by alamb** [comment]
BTW I think the core problem here is that DataFusion's parallel hash grouping builds the entire hash table for each input partition -- thus it requires memory proportional to the number of cores. This is tracked more in https://github.com/apache/arrow-datafusion/issues/6937

**Comment by alamb** [comment]
I spent some time analyzing why `Q17` and `Q18` are slow in detail this morning (in the context of #6782 ). My analysis shows we could close most of the gap with a better join order:

* https://github.com/apache/arrow-datafusion/issues/7949
* https://github.com/apache/arrow-datafusion/issues/7950

**Comment by korowa** [comment]
The issue seems to be (at least partially) related to `FilterExec` returning [unknown](https://github.com/apache/arrow-datafusion/blob/308c35404939ed39e4e398054d6fc78c89817109/datafusion/physical-plan/src/filter.rs#L199) statistics in case of unsupported filter predicates -- I wonder, if it would be better / more correct to rely on worth-case scenario for such filters, and simply propagate input statistics -- it seems to be enough to fix Q17 plan.

**Comment by alamb** [comment]
>  I wonder, if it would be better / more correct to rely on worth-case scenario for such filters, and simply propagate input statistics

Perhaps the filter can simply switch to `Precision::Inexact` when it can't analyze the selectivity for the expression

Another thing I have seen in the past is heuristically pick a constant selectivity (assume it filters 1/2 the rows). However I think this leads to non-robust plans (sometimes the plans are good, sometimes they are bad, and it is hard to predict when each is hit)

**Comment by alamb** [comment]
I filed https://github.com/apache/arrow-datafusion/issues/8078 with a proposal of a more precise way to represent inexact statistics

**Comment by djouallah** [comment]
Thank you very much for your works, I am happy with datafusion 33 performance,  now it does finish TPCH_SF100 using 64 GB of RAM in Fabric
