### ISSUE TITLE
Project output ordering at the source

### ISSUE THREAD

**Issue by mustafasrepo** [apache/arrow-datafusion#6118]
### Describe the bug

Assume that input source is already ordered by `Column a`. Also assume that it consists of Columns a,b (with this order in the schema). When I run the query below.
```sql
SELECT a FROM annotated_data
  ORDER BY a
``` 
It produces following plan
``` 
"CsvExec: files={1 group: [[FILE_PATH]]}, has_header=true, limit=None, projection=[a]",
``` 
However, If input source schema were consist of Columns b, a (with this order in the schema). The query above produces following plan
``` 
"SortExec: expr=[a@0 ASC NULLS LAST]",
"  CsvExec: files={1 group: [[FILE_PATH]]}, has_header=true, limit=None, projection=[a]",
``` 

### Expected behavior

I expect for second case to not produce `SortExec` in its physical plan.

### Additional context

I think during `output_ordering` calculation for sources, we do not consider projection information. Hence `output_ordering` generated may not always be valid.

**Comment by mingmwang** [comment]
I fixed a bug related to the `output_ordering` and `output_partitioning` in `ProjectionExec`.  I'm not sure whether it is related or not, looks like it is related to the projection pushed down to the scan ?

**Comment by mustafasrepo** [comment]
> I fixed a bug related to the `output_ordering` and `output_partitioning` in `ProjectionExec`. I'm not sure whether it is related or not, looks like it is related to the projection pushed down to the scan ?

I have verified that after your fix is introduced. This problem still occurs. I traced the bug, it is related to the projection pushed down to the scan. Source doesn't use projection information during calculation of `output_ordering`. I will probably file a fix for this bug today.
